# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mosquito_alert.api.token_api import TokenApi


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TokenApi()

    def tearDown(self) -> None:
        pass

    def test_token_create(self) -> None:
        """Test case for token_create

        """
        pass

    def test_token_refresh_create(self) -> None:
        """Test case for token_refresh_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
