# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mosquito_alert.api.countries_api import CountriesApi


class TestCountriesApi(unittest.TestCase):
    """CountriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CountriesApi()

    def tearDown(self) -> None:
        pass

    def test_countries_retrieve(self) -> None:
        """Test case for countries_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
