# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mosquito_alert.models.country_permission import CountryPermission

class TestCountryPermission(unittest.TestCase):
    """CountryPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CountryPermission:
        """Test CountryPermission
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CountryPermission`
        """
        model = CountryPermission()
        if include_optional:
            return CountryPermission(
                role = 'base',
                permissions = mosquito_alert.models.permissions.Permissions(
                    annotation = mosquito_alert.models.annotation_permission.AnnotationPermission(
                        add = True, 
                        change = True, 
                        view = True, 
                        delete = True, 
                        mark_as_decisive = True, ), 
                    identification_task = mosquito_alert.models.identification_task_permission.IdentificationTaskPermission(
                        add = True, 
                        change = True, 
                        view = True, 
                        delete = True, ), 
                    review = mosquito_alert.models.review_permission.ReviewPermission(
                        add = True, 
                        change = True, 
                        view = True, 
                        delete = True, ), ),
                country = mosquito_alert.models.country.Country(
                    id = 56, 
                    name_en = '', 
                    iso3_code = '', )
            )
        else:
            return CountryPermission(
                role = 'base',
                permissions = mosquito_alert.models.permissions.Permissions(
                    annotation = mosquito_alert.models.annotation_permission.AnnotationPermission(
                        add = True, 
                        change = True, 
                        view = True, 
                        delete = True, 
                        mark_as_decisive = True, ), 
                    identification_task = mosquito_alert.models.identification_task_permission.IdentificationTaskPermission(
                        add = True, 
                        change = True, 
                        view = True, 
                        delete = True, ), 
                    review = mosquito_alert.models.review_permission.ReviewPermission(
                        add = True, 
                        change = True, 
                        view = True, 
                        delete = True, ), ),
                country = mosquito_alert.models.country.Country(
                    id = 56, 
                    name_en = '', 
                    iso3_code = '', ),
        )
        """

    def testCountryPermission(self):
        """Test CountryPermission"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
