# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mosquito_alert_api.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_notifications_create(self) -> None:
        """Test case for notifications_create

        """
        pass

    def test_notifications_list(self) -> None:
        """Test case for notifications_list

        """
        pass

    def test_notifications_partial_update(self) -> None:
        """Test case for notifications_partial_update

        """
        pass

    def test_notifications_retrieve(self) -> None:
        """Test case for notifications_retrieve

        """
        pass

    def test_notifications_update(self) -> None:
        """Test case for notifications_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
