# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mosquito_alert.api.observations_api import ObservationsApi


class TestObservationsApi(unittest.TestCase):
    """ObservationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObservationsApi()

    def tearDown(self) -> None:
        pass

    def test_observations_create(self) -> None:
        """Test case for observations_create

        """
        pass

    def test_observations_destroy(self) -> None:
        """Test case for observations_destroy

        """
        pass

    def test_observations_list(self) -> None:
        """Test case for observations_list

        """
        pass

    def test_observations_prediction_create(self) -> None:
        """Test case for observations_prediction_create

        """
        pass

    def test_observations_prediction_destroy(self) -> None:
        """Test case for observations_prediction_destroy

        """
        pass

    def test_observations_prediction_retrieve(self) -> None:
        """Test case for observations_prediction_retrieve

        """
        pass

    def test_observations_retrieve(self) -> None:
        """Test case for observations_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
