# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mosquito_alert.api.boundaries_api import BoundariesApi


class TestBoundariesApi(unittest.TestCase):
    """BoundariesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BoundariesApi()

    def tearDown(self) -> None:
        pass

    def test_create_temporary(self) -> None:
        """Test case for create_temporary

        """
        pass


if __name__ == '__main__':
    unittest.main()
