# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mosquito_alert_api.models.bite_request import BiteRequest

class TestBiteRequest(unittest.TestCase):
    """BiteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BiteRequest:
        """Test BiteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BiteRequest`
        """
        model = BiteRequest()
        if include_optional:
            return BiteRequest(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sent_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location = mosquito_alert_api.models.report_location_request.ReportLocationRequest(
                    type = 'current', 
                    point = mosquito_alert_api.models.report_location_point.ReportLocation_point(
                        latitude = 1.337, 
                        longitude = 1.337, ), ),
                note = '',
                tags = [
                    '0'
                    ],
                package = mosquito_alert_api.models.package_request.PackageRequest(
                    name = '', 
                    version = -2147483648, 
                    language = '', ),
                device = mosquito_alert_api.models.device_request.DeviceRequest(
                    manufacturer = '', 
                    model = '', 
                    os = '', 
                    os_version = '', 
                    os_language = '', ),
                event_environment = 'indoors',
                event_moment = 'now',
                head_bite_count = 56,
                left_arm_bite_count = 56,
                right_arm_bite_count = 56,
                chest_bite_count = 56,
                left_leg_bite_count = 56,
                right_leg_bite_count = 56
            )
        else:
            return BiteRequest(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sent_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location = mosquito_alert_api.models.report_location_request.ReportLocationRequest(
                    type = 'current', 
                    point = mosquito_alert_api.models.report_location_point.ReportLocation_point(
                        latitude = 1.337, 
                        longitude = 1.337, ), ),
        )
        """

    def testBiteRequest(self):
        """Test BiteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
