# coding: utf-8

"""
    Mosquito Alert API

    Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.

    The version of the OpenAPI document: v1
    Contact: it@mosquitoalert.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LocalizedMessageBody(BaseModel):
    """
    A custom serializer field that supports localization for a dynamic field name. Allows calling with arguments such as 'title', 'message', max_length, help_text, etc.
    """ # noqa: E501
    bg: Optional[StrictStr] = Field(default=None, description="Български")
    bn: Optional[StrictStr] = Field(default=None, description="বাংলা")
    ca: Optional[StrictStr] = Field(default=None, description="Català")
    de: Optional[StrictStr] = Field(default=None, description="Deutsch")
    el: Optional[StrictStr] = Field(default=None, description="Ελληνικά")
    en: Optional[StrictStr] = Field(default=None, description="English")
    es: Optional[StrictStr] = Field(default=None, description="Español")
    eu: Optional[StrictStr] = Field(default=None, description="Basque")
    fr: Optional[StrictStr] = Field(default=None, description="Français")
    gl: Optional[StrictStr] = Field(default=None, description="Galego")
    hr: Optional[StrictStr] = Field(default=None, description="Hrvatski")
    hu: Optional[StrictStr] = Field(default=None, description="Magyar")
    it: Optional[StrictStr] = Field(default=None, description="Italiano")
    lb: Optional[StrictStr] = Field(default=None, description="Lëtzebuergesch")
    mk: Optional[StrictStr] = Field(default=None, description="Македонски")
    nl: Optional[StrictStr] = Field(default=None, description="Nederlands")
    pt: Optional[StrictStr] = Field(default=None, description="Português")
    ro: Optional[StrictStr] = Field(default=None, description="Română")
    sl: Optional[StrictStr] = Field(default=None, description="Slovenščina")
    sq: Optional[StrictStr] = Field(default=None, description="Shqip")
    sr: Optional[StrictStr] = Field(default=None, description="Српски")
    sv: Optional[StrictStr] = Field(default=None, description="Svenska")
    tr: Optional[StrictStr] = Field(default=None, description="Türkçe")
    zh_cn: Optional[StrictStr] = Field(default=None, description="简体中文", alias="zh-cn")
    __properties: ClassVar[List[str]] = ["bg", "bn", "ca", "de", "el", "en", "es", "eu", "fr", "gl", "hr", "hu", "it", "lb", "mk", "nl", "pt", "ro", "sl", "sq", "sr", "sv", "tr", "zh-cn"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LocalizedMessageBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bg (nullable) is None
        # and model_fields_set contains the field
        if self.bg is None and "bg" in self.model_fields_set:
            _dict['bg'] = None

        # set to None if bn (nullable) is None
        # and model_fields_set contains the field
        if self.bn is None and "bn" in self.model_fields_set:
            _dict['bn'] = None

        # set to None if ca (nullable) is None
        # and model_fields_set contains the field
        if self.ca is None and "ca" in self.model_fields_set:
            _dict['ca'] = None

        # set to None if de (nullable) is None
        # and model_fields_set contains the field
        if self.de is None and "de" in self.model_fields_set:
            _dict['de'] = None

        # set to None if el (nullable) is None
        # and model_fields_set contains the field
        if self.el is None and "el" in self.model_fields_set:
            _dict['el'] = None

        # set to None if en (nullable) is None
        # and model_fields_set contains the field
        if self.en is None and "en" in self.model_fields_set:
            _dict['en'] = None

        # set to None if es (nullable) is None
        # and model_fields_set contains the field
        if self.es is None and "es" in self.model_fields_set:
            _dict['es'] = None

        # set to None if eu (nullable) is None
        # and model_fields_set contains the field
        if self.eu is None and "eu" in self.model_fields_set:
            _dict['eu'] = None

        # set to None if fr (nullable) is None
        # and model_fields_set contains the field
        if self.fr is None and "fr" in self.model_fields_set:
            _dict['fr'] = None

        # set to None if gl (nullable) is None
        # and model_fields_set contains the field
        if self.gl is None and "gl" in self.model_fields_set:
            _dict['gl'] = None

        # set to None if hr (nullable) is None
        # and model_fields_set contains the field
        if self.hr is None and "hr" in self.model_fields_set:
            _dict['hr'] = None

        # set to None if hu (nullable) is None
        # and model_fields_set contains the field
        if self.hu is None and "hu" in self.model_fields_set:
            _dict['hu'] = None

        # set to None if it (nullable) is None
        # and model_fields_set contains the field
        if self.it is None and "it" in self.model_fields_set:
            _dict['it'] = None

        # set to None if lb (nullable) is None
        # and model_fields_set contains the field
        if self.lb is None and "lb" in self.model_fields_set:
            _dict['lb'] = None

        # set to None if mk (nullable) is None
        # and model_fields_set contains the field
        if self.mk is None and "mk" in self.model_fields_set:
            _dict['mk'] = None

        # set to None if nl (nullable) is None
        # and model_fields_set contains the field
        if self.nl is None and "nl" in self.model_fields_set:
            _dict['nl'] = None

        # set to None if pt (nullable) is None
        # and model_fields_set contains the field
        if self.pt is None and "pt" in self.model_fields_set:
            _dict['pt'] = None

        # set to None if ro (nullable) is None
        # and model_fields_set contains the field
        if self.ro is None and "ro" in self.model_fields_set:
            _dict['ro'] = None

        # set to None if sl (nullable) is None
        # and model_fields_set contains the field
        if self.sl is None and "sl" in self.model_fields_set:
            _dict['sl'] = None

        # set to None if sq (nullable) is None
        # and model_fields_set contains the field
        if self.sq is None and "sq" in self.model_fields_set:
            _dict['sq'] = None

        # set to None if sr (nullable) is None
        # and model_fields_set contains the field
        if self.sr is None and "sr" in self.model_fields_set:
            _dict['sr'] = None

        # set to None if sv (nullable) is None
        # and model_fields_set contains the field
        if self.sv is None and "sv" in self.model_fields_set:
            _dict['sv'] = None

        # set to None if tr (nullable) is None
        # and model_fields_set contains the field
        if self.tr is None and "tr" in self.model_fields_set:
            _dict['tr'] = None

        # set to None if zh_cn (nullable) is None
        # and model_fields_set contains the field
        if self.zh_cn is None and "zh_cn" in self.model_fields_set:
            _dict['zh-cn'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LocalizedMessageBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bg": obj.get("bg"),
            "bn": obj.get("bn"),
            "ca": obj.get("ca"),
            "de": obj.get("de"),
            "el": obj.get("el"),
            "en": obj.get("en"),
            "es": obj.get("es"),
            "eu": obj.get("eu"),
            "fr": obj.get("fr"),
            "gl": obj.get("gl"),
            "hr": obj.get("hr"),
            "hu": obj.get("hu"),
            "it": obj.get("it"),
            "lb": obj.get("lb"),
            "mk": obj.get("mk"),
            "nl": obj.get("nl"),
            "pt": obj.get("pt"),
            "ro": obj.get("ro"),
            "sl": obj.get("sl"),
            "sq": obj.get("sq"),
            "sr": obj.get("sr"),
            "sv": obj.get("sv"),
            "tr": obj.get("tr"),
            "zh-cn": obj.get("zh-cn")
        })
        return _obj


